name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Required for pushing commits

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: |
        git config --global user.name "mdayan8"
        git config --global user.email "mdayanbag@gmail.com"

    - name: Make daily commit
      run: |
        # Add current date and time to daily.md
        echo "🕒 $(date)" >> daily.md
        
        # Check if there are changes to commit
        if git diff --quiet daily.md; then
          echo "No changes to commit"
          exit 0
        fi
        
        # Stage and commit changes
        git add daily.md
        git commit -m "📅 Daily update: $(date +'%Y-%m-%d %H:%M UTC')"

    - name: Push changes
      run: |
        git push origin main
