name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Git Identity
        run: |
          git config --global user.email "mdayanbag@gmail.com"
          git config --global user.name "mdayan8"

      - name: Make daily log entry
        run: echo "$(date)" >> daily.md

      - name: Commit changes
        run: |
          git add daily.md
          git commit -m "docs: daily log $(date +'%Y-%m-%d')" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
